import {
  AdminReviewItem,
  FarmProfile,
  InvestorProfile,
  OperatorProfile,
} from '@ai-sprints/shared-types';

export const seedFarms: FarmProfile[] = [
  {
    id: 'farm-001',
    operatorId: 'op-001',
    name: 'Nile Delta Wheat Cooperative',
    country: 'Egypt',
    region: 'Delta',
    governorate: 'Beheira',
    latitude: 30.8481,
    longitude: 30.3436,
    areaHectares: 45,
    soilType: 'clay',
    waterSource: 'nile',
    currentCrop: 'wheat',
    plannedCrops: ['wheat', 'corn'],
    requestedCapitalUsd: 85000,
    projectedRoiPercent: 14,
    cropCycleDays: 120,
    yieldHistory: [
      { year: 2023, cropName: 'wheat', tonnesPerHectare: 4.2, revenueUsd: 72000 },
      { year: 2024, cropName: 'wheat', tonnesPerHectare: 4.5, revenueUsd: 78000 },
    ],
    certifications: ['GlobalG.A.P.'],
    documentUrls: [],
    imageUrls: [],
    status: 'active',
    aiProfileSummary:
      'Established wheat cooperative with 2-year yield history and Nile irrigation access. Consistent yield growth of 7% year-over-year. Low operational risk.',
    createdAt: '2025-01-15T09:00:00Z',
    updatedAt: '2025-03-01T09:00:00Z',
  },
  {
    id: 'farm-002',
    operatorId: 'op-002',
    name: 'Upper Egypt Citrus Estate',
    country: 'Egypt',
    region: 'Upper Egypt',
    governorate: 'Luxor',
    latitude: 25.6872,
    longitude: 32.6396,
    areaHectares: 28,
    soilType: 'sandy',
    waterSource: 'groundwater',
    currentCrop: 'citrus',
    plannedCrops: ['citrus', 'mango'],
    requestedCapitalUsd: 120000,
    projectedRoiPercent: 19,
    cropCycleDays: 270,
    yieldHistory: [
      { year: 2024, cropName: 'citrus', tonnesPerHectare: 18, revenueUsd: 95000 },
    ],
    certifications: ['Organic Egypt', 'Fair Trade'],
    documentUrls: [],
    imageUrls: [],
    status: 'active',
    aiProfileSummary:
      'Premium citrus estate in Luxor governorate with dual organic certifications. High ROI projection driven by export-grade fruit quality. Groundwater dependency is manageable at current depth.',
    createdAt: '2025-02-10T10:00:00Z',
    updatedAt: '2025-04-15T10:00:00Z',
  },
  {
    id: 'farm-003',
    operatorId: 'op-003',
    name: 'Fayoum Tomato & Potato Farm',
    country: 'Egypt',
    region: 'Fayoum',
    governorate: 'Fayoum',
    latitude: 29.3084,
    longitude: 30.8428,
    areaHectares: 15,
    soilType: 'loamy',
    waterSource: 'irrigation_canal',
    currentCrop: 'tomato',
    plannedCrops: ['tomato', 'potato', 'onion'],
    requestedCapitalUsd: 45000,
    projectedRoiPercent: 22,
    cropCycleDays: 90,
    yieldHistory: [
      { year: 2023, cropName: 'tomato', tonnesPerHectare: 35, revenueUsd: 42000 },
      { year: 2024, cropName: 'potato', tonnesPerHectare: 22, revenueUsd: 38000 },
    ],
    certifications: [],
    documentUrls: [],
    imageUrls: [],
    status: 'active',
    aiProfileSummary:
      'High-yield vegetable farm in Fayoum oasis with irrigation canal access. Short 90-day crop cycles provide excellent capital velocity. Diversified crop rotation reduces single-crop risk.',
    createdAt: '2025-03-01T08:00:00Z',
    updatedAt: '2025-05-01T08:00:00Z',
  },
  {
    id: 'farm-004',
    operatorId: 'op-004',
    name: 'Sinai Olive Grove Project',
    country: 'Egypt',
    region: 'Sinai',
    governorate: 'North Sinai',
    latitude: 30.9253,
    longitude: 33.7925,
    areaHectares: 60,
    soilType: 'chalky',
    waterSource: 'groundwater',
    currentCrop: 'olive',
    plannedCrops: ['olive'],
    requestedCapitalUsd: 200000,
    projectedRoiPercent: 16,
    cropCycleDays: 270,
    yieldHistory: [],
    certifications: ['Mediterranean Organic'],
    documentUrls: [],
    imageUrls: [],
    status: 'pending_review',
    aiProfileSummary:
      'New olive cultivation project on reclaimed Sinai land. No yield history yet. Mediterranean organic certification adds export value. High capital requirement warrants thorough due diligence.',
    createdAt: '2025-05-05T11:00:00Z',
    updatedAt: '2025-05-05T11:00:00Z',
  },
  {
    id: 'farm-005',
    operatorId: 'op-005',
    name: 'Aswan Sugarcane Plantation',
    country: 'Egypt',
    region: 'Upper Egypt',
    governorate: 'Aswan',
    latitude: 24.0889,
    longitude: 32.8998,
    areaHectares: 80,
    soilType: 'clay',
    waterSource: 'nile',
    currentCrop: 'sugarcane',
    plannedCrops: ['sugarcane'],
    requestedCapitalUsd: 175000,
    projectedRoiPercent: 20,
    cropCycleDays: 365,
    yieldHistory: [
      { year: 2022, cropName: 'sugarcane', tonnesPerHectare: 75, revenueUsd: 130000 },
      { year: 2023, cropName: 'sugarcane', tonnesPerHectare: 80, revenueUsd: 142000 },
      { year: 2024, cropName: 'sugarcane', tonnesPerHectare: 82, revenueUsd: 148000 },
    ],
    certifications: ['GlobalG.A.P.', 'Rainforest Alliance'],
    documentUrls: [],
    imageUrls: [],
    status: 'active',
    aiProfileSummary:
      'Mature sugarcane plantation with 3-year consistent growth trend. Nile irrigation and dual certifications support premium pricing. Long 365-day cycle requires patient capital with strong returns.',
    createdAt: '2024-11-01T07:00:00Z',
    updatedAt: '2025-04-01T07:00:00Z',
  },
];

export const seedInvestors: InvestorProfile[] = [
  {
    id: 'inv-001',
    userId: 'user-001',
    name: 'Ahmed Mansour',
    preferences: {
      investorId: 'inv-001',
      riskTolerance: 'medium',
      investmentHorizonMonths: 12,
      capitalBudgetUsd: 100000,
      liquidityPreference: 'medium',
      preferredCrops: ['wheat', 'citrus', 'tomato'],
      preferredRegions: ['Delta', 'Fayoum'],
      expectedRoiPercent: 15,
      sustainabilityFocus: true,
    },
    portfolio: [],
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
];

export const seedOperators: OperatorProfile[] = [
  { id: 'op-001', userId: 'user-op-001', name: 'Mohamed Hassan', phone: '+20-100-000-0001', whatsappNumber: '+20-100-000-0001', region: 'Delta', farmIds: ['farm-001'], verificationStatus: 'verified', createdAt: '2025-01-01T00:00:00Z' },
  { id: 'op-002', userId: 'user-op-002', name: 'Fatima Ibrahim', phone: '+20-100-000-0002', whatsappNumber: '+20-100-000-0002', region: 'Upper Egypt', farmIds: ['farm-002'], verificationStatus: 'verified', createdAt: '2025-01-01T00:00:00Z' },
  { id: 'op-003', userId: 'user-op-003', name: 'Karim Saleh', phone: '+20-100-000-0003', whatsappNumber: '+20-100-000-0003', region: 'Fayoum', farmIds: ['farm-003'], verificationStatus: 'verified', createdAt: '2025-01-01T00:00:00Z' },
  { id: 'op-004', userId: 'user-op-004', name: 'Layla Mostafa', phone: '+20-100-000-0004', whatsappNumber: '+20-100-000-0004', region: 'Sinai', farmIds: ['farm-004'], verificationStatus: 'pending', createdAt: '2025-01-01T00:00:00Z' },
  { id: 'op-005', userId: 'user-op-005', name: 'Omar Abdel-Aziz', phone: '+20-100-000-0005', whatsappNumber: '+20-100-000-0005', region: 'Upper Egypt', farmIds: ['farm-005'], verificationStatus: 'verified', createdAt: '2025-01-01T00:00:00Z' },
];

export const seedReviewItems: AdminReviewItem[] = [
  {
    id: 'review-001',
    itemType: 'farm_profile',
    targetId: 'farm-004',
    status: 'pending',
    aiSummary:
      'New olive farm in North Sinai. No yield history. Mediterranean organic certification noted. Capital request of $200K is above average. Recommend verification of land title and water access permit.',
    flags: [
      { severity: 'medium', label: 'No Yield History', detail: 'Farm has not submitted any historical yield data.' },
      { severity: 'low', label: 'High Capital Request', detail: '$200K exceeds median for first-time operator farms.' },
    ],
    createdAt: '2025-05-05T11:00:00Z',
    updatedAt: '2025-05-05T11:00:00Z',
  },
  {
    id: 'review-002',
    itemType: 'deal_recommendation',
    targetId: 'deal-farm-002-inv-001',
    status: 'pending',
    aiSummary:
      'Revenue share deal recommended for Upper Egypt Citrus Estate. $96K investment, 17.1% projected ROI. High AI confidence based on 1 year yield data and dual certifications.',
    flags: [
      { severity: 'low', label: 'Single Year History', detail: 'Only 1 year of yield data available - limited baseline.' },
    ],
    createdAt: '2025-05-10T14:00:00Z',
    updatedAt: '2025-05-10T14:00:00Z',
  },
  {
    id: 'review-003',
    itemType: 'alert',
    targetId: 'alert-1',
    status: 'pending',
    aiSummary:
      'Critical weather alert for Delta region. Heavy rainfall projected - 95mm over 3 days. Affects 1 active farm. Operator notification via WhatsApp recommended.',
    flags: [
      { severity: 'high', label: 'Critical Weather Risk', detail: 'Rainfall exceeds 80mm threshold triggering flood risk protocols.' },
    ],
    createdAt: '2025-05-12T08:00:00Z',
    updatedAt: '2025-05-12T08:00:00Z',
  },
];
